name: Deploy frontend to S3

on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        working-directory: ./frontend
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Rebuild the dist/ directory
        working-directory: ./frontend
        run: npm run build

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'frontend/build'
          destination_dir: ''