name: Deploy backend to Lambda

on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2

      - uses: aws-actions/setup-sam@v1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - working-directory: ./backend
        run: sam build -m requirements.txt --use-container

      - working-directory: ./backend
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name algorhythms --s3-bucket algorhythms-backend --capabilities CAPABILITY_IAM --region us-east-1